[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_movie_review_program = "EQAtYPrPtSNyJT4MBsdhnysgofEEZooq5A8kZ1umnUp8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sujoynath/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
